app = 'monefy-bot-lingering-bird-6761'

[build]
  dockerfile = "Dockerfile"  # Явное указание Dockerfile

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Главное исправление!
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  interval = "15s"  # Увеличенный интервал
  timeout = "5s"    # Увеличенный таймаут
  grace_period = "5s"
  method = "GET"
  path = "/health"  # Должен быть реализован в вашем боте
